### ISSUE TITLE
Tumblr での Todos

### ISSUE THREAD

**Issue by karur4n** [MokumokuCloud/podcasting#1]
- [x] タイトルを決める https://github.com/MokumokuCloud/podcasting/issues/1#issuecomment-85000042
- [x] テーマの変更 https://github.com/MokumokuCloud/podcasting/issues/4
- [x] ヘッダー画像を設定する
- [ ] favicon を設置する
- [x] 説明文の記述
- [x] ポストの書式を決める https://github.com/MokumokuCloud/podcasting/issues/1#issuecomment-87760387
- [x] パーソナリティ部のスタイリング #6 
- [ ] プレイヤーライブラリの選定
  - サンプルだと HTML 5 のタグ
  - Rebuild.fm だと [MediaElement.js](http://mediaelementjs.com/)
  - wada.fm だと [JW Player](http://www.jwplayer.com/) が使われている
    - [JW Player | AAC or MP3 Audio Embed](http://support.jwplayer.com/customer/portal/articles/1406724-aac-or-mp3-audio-embed)

**Comment by gaaamii** [comment]
個人的にははとりあえずこのまま mokumoku-cloud podcastで良いと思います。

**Comment by karur4n** [comment]
わかりました、そうしておきましょうか。

僕的にはもう少し短くて呼びやすい名前がいいと思うので、良いのあったら提案します :sunglasses:

**Comment by yoshiso** [comment]
idea投げるだけ
mokumoku cast

**Comment by karur4n** [comment]
よい

Podcast の語源は iPod + Broadcast なんで pod なくてもいいですしね

**Comment by karur4n** [comment]
mo(kumo)ku  と Cloud（雲）で kumo cast（（雲 / くも）キャスト）  はどうですか？

**Comment by gaaamii** [comment]
良いっすね。表記はどうしましょう
- Kumocast
- kumocast
- Kumo Cast
- 雲キャスト
- くもキャスト
- クモキャスト

**Comment by karur4n** [comment]
- 雲キャスト
- くもキャスト

どちらかが良いと思います。「くもキャスト」かな。

**Comment by gaaamii** [comment]
ひらがな好きなので、くもキャストに一票！kumocast.tumblr.com にしてドメインも合わせます？

**Comment by karur4n** [comment]
そうしましょう！

**Comment by karur4n** [comment]
変更しました

http://kumocast.tumblr.com/

**Comment by gaaamii** [comment]
ありがとうございます！！！

**Comment by karur4n** [comment]
アイコンを作ることが一番難儀しそうですね…… :cloud:

**Comment by gaaamii** [comment]
たしかに...。

**Comment by gaaamii** [comment]
ヘッダー画像あたりに使えるものが見つかるかも
- [2週間ごとに著作権放棄された写真を公開・配布するストックフォトサービス・「stokpic」](http://kachibito.net/useful-resource/stokpic)
- [stokpic](http://stokpic.com/)

**Comment by gaaamii** [comment]
この写真すごい良い。
- http://stokpic.com/project/concept-of-man-holding-ipad-in-front-of-face-with-clouds-and-countryside/

**Comment by karur4n** [comment]
かなり良いっすね :sparkles: 

![photo](http://stokpic.com/wp-content/uploads/2014/11/Concept-Of-Man-Holding-iPad-In-Front-Of-Face-With-Clouds-And-Countryside.jpg)

**Comment by karur4n** [comment]
雑にアイコン作るとこんな感じになりました

![kumocast](https://cloud.githubusercontent.com/assets/6816398/6819869/aac6bc9e-d30b-11e4-9653-2b7d436332e6.png)

![kumocast_sm](https://cloud.githubusercontent.com/assets/6816398/6819904/1d7d7de0-d30c-11e4-9142-f0171e24f323.png)

**Comment by gaaamii** [comment]
最高ですね :+1:

**Comment by karur4n** [comment]
カバーアートは最低でも 1400×1400 ないとダメだから、近々 大きいものも作りますね。

しかし、もう少しデザイン励みたい（笑

**Comment by karur4n** [comment]
プレイヤーは、Rebuild で使われているものが 再生速度変更できて良さそうですね。採用したい。

[MediaElement.js - HTML5 video player and audio player with Flash and Silverlight shims](http://mediaelementjs.com/)

**Comment by karur4n** [comment]
良さそうなテーマ
- https://www.tumblr.com/theme/39138
- https://www.tumblr.com/theme/39279
- https://www.tumblr.com/theme/39615
- https://www.tumblr.com/theme/38963
- https://www.tumblr.com/theme/38338

この issue, 主語がでかくて 1 つのスレッドで全て議論するの良くない

**Comment by karur4n** [comment]
ポストの書式は日々練磨しながら posts/example.txt で共有していきましょう

https://github.com/MokumokuCloud/podcasting/blob/master/posts/example.txt

**Comment by gaaamii** [comment]
- http://kumocast.jp

に移行してくれたのでこちらも閉じます
