### ISSUE TITLE
フィード生成とiTunesへの登録

### ISSUE THREAD

**Issue by gaaamii** [MokumokuCloud/podcasting#3]

**Comment by gaaamii** [comment]
ひとまずできました。
- http://feeds.feedburner.com/tumblr/wuDk

**Comment by gaaamii** [comment]
これをAppleに申請して通れば配信されるようになると思います。
ただ、画像のサイズが小さいのでそこは申請する前に修正しておきたいですね。

**Comment by gaaamii** [comment]
それと、申請前に本番配付用のエピソードを収録してアップロードしておかなくてはいけないと思うので、申請は最終段階ですね

**Comment by karur4n** [comment]
おつかれさまです！！！

![bijo](http://hisaichilgtm.herokuapp.com/http://31.media.tumblr.com/28f3d7265c5160ff45e4e8d9872df594/tumblr_nlku7fepYY1rg5596o2_400.gif)

なるほどなるほど

**Comment by gaaamii** [comment]
美女だ！
あと、登録情報はとりあえずてきとーに入れてしまったのでwikiで管理するようにしときます！

**Comment by gaaamii** [comment]
[iTunesの登録情報](https://github.com/MokumokuCloud/podcasting/wiki/iTunes%E3%81%AE%E7%99%BB%E9%8C%B2%E6%83%85%E5%A0%B1)
