### ISSUE TITLE
挨拶用の台本

### ISSUE THREAD

**Issue by gaaamii** [MokumokuCloud/podcasting#5]
「こんにちは。第◯回 Kumocast です。〜〜〜」
「今回は...と・・・についてお送りしました。〜〜〜」
みたいな

**Comment by gaaamii** [comment]
はじめ：「こんにちは。第◯回 Kumocast です。このPodcastは独学でプログラミングを学ぶ若者たちがゆるくつながってお話をしたりしている、その様子を配信するPodcastです。」

**Comment by gaaamii** [comment]
おわり：「では、本日の第◯回 Kumocast, 参加してくれたのは, ...、...でした。では、また来週！」

**Comment by gaaamii** [comment]
ゲストを呼んだときの紹介の流れも台本化したい

**Comment by karur4n** [comment]
はじめの挨拶に加えて

「今回は 〇〇 さんに来ていただいてます。自己紹介お願いします。」
「〜〜〜〜〜〜〜」
「では 〇〇 さん、よろしくお願いします。」

くらいな感じで良いと思います

**Comment by gaaamii** [comment]
:+1:

**Comment by gaaamii** [comment]
閉じます
