### ISSUE TITLE
パーソナリティ部のスタイリング

### ISSUE THREAD

**Issue by karur4n** [MokumokuCloud/podcasting#6]
雑に以下のようにマークアップするとこんな感じ

``` markdown
## パーソナリティ

### gaaamii

![](https://avatars3.githubusercontent.com/u/4538656?v=3&s=140)

### karur4n

![](https://avatars3.githubusercontent.com/u/6816398?v=3&s=140)

```

![2015-03-31 0 42 15](https://cloud.githubusercontent.com/assets/6816398/6899997/cc7b8874-d73e-11e4-809f-a64fb53f4729.png)

**Comment by gaaamii** [comment]
おおー、やっぱプロフィールアイコンあると良いですねー :)

**Comment by karur4n** [comment]
こんな感じにしました

![2015-03-31 2 12 39](https://cloud.githubusercontent.com/assets/6816398/6901936/7b59e12c-d74b-11e4-894a-16665be5bf88.png)

**Comment by karur4n** [comment]
マークアップは posts/example.txt を見てください
