### ISSUE TITLE
Podcast の information を綺麗にしたい

### ISSUE THREAD

**Issue by karur4n** [MokumokuCloud/podcasting#7]
## 現状

Show Notes がリストになってなかったり、改行がなかったりで読みづらい

![img_0563](https://cloud.githubusercontent.com/assets/6816398/6991146/4ab699fe-dabe-11e4-9988-5b89c5202ce6.PNG)
## 目指したい

こんな感じにしたい

![img_0564](https://cloud.githubusercontent.com/assets/6816398/6991147/4ce6c41a-dabe-11e4-9467-19b8a758b5a1.PNG)

![img_0565](https://cloud.githubusercontent.com/assets/6816398/6991148/4f66f61a-dabe-11e4-9d68-1af8283db953.PNG)

**Comment by gaaamii** [comment]
こちらもOKですね
