### ISSUE TITLE
Jekyllへの移行

### ISSUE THREAD

**Issue by gaaamii** [MokumokuCloud/podcasting#9]
移行する際のメリット・デメリット・Jekyllにしたときのワークフローなど話しあいましょう

**Comment by karur4n** [comment]
まだ完成していなのですが http://kumocast.github.io/ で見られます。

Jekyll は GitHub がサポートしているので、作って出来上がったディレクトリを push するするだけで Pages として閲覧できてとりあえず良いです。

**Comment by karur4n** [comment]
## Jekyll の良くないところ

新しい Post を作るときに

```
$ touch _posts/2015-04-15-title.md
```

ってするのがめんどくさい。Post のテンプレートから new Post を生成できるようにしてほしい。

**Comment by gaaamii** [comment]
なるほど。そこは自前でどうにかすれば良さそうですね。

ドメインどうするかで迷ってるんですが、どうしましょうかね。github pagesのドメインのままにするか、ドメインとってどうにかするか。

今後もずっと今の構成で続けるなら問題ないと思うんですが、今回の移行みたいなのが頻繁に起こりそうなら僕の方でくもキャストのドメインをとろうかと思うんですが。

**Comment by karur4n** [comment]
GitHub Pages じゃ物足りなくなるシーンが出てくるかどうかですね。

音声のホスティングやライブ配信のために VPS 借りるようになったりすると、柔軟性のためにページもそこに置きたくなるので移行することになると思います。

そういうときが来るのかどうか。
